version: '3'

services:
  server:
    build: .
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DB_HOST: postgresql
      DB_USER: adonis
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: adonis_db
    depends_on:
      - postgresql
    command: sh -c "node ace migration:run && node bin/server.js"

  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: adonis_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  cdn:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./build/public/assets:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata: